services:
  backend:
    build: ./backend
    container_name: electolibrary-backend
    ports:
      - "8000:8000"
    environment:
      DB_PATH: /app/data/tasks.db
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./data:/app/data
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: electolibrary-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
